In [34]:
from datetime import datetime
import requests
import numpy as np
import pandas as pd

In [77]:
num = 1440
#end_time = datetime.now().strftime('%s')  # 現在時刻(UNIXタイム)取得
end_time = datetime(2016, 12, 31, 23, 59).strftime('%s')
start_time = str( int(end_time) - 60*num )

In [78]:
start_time, end_time

('1483109940', '1483196340')

In [79]:
com = "https://www.bitmex.com/api/udf/history?symbol=XBTUSD&resolution=1&from={0:}&to={1:}".format(start_time, end_time)

In [80]:
com

'https://www.bitmex.com/api/udf/history?symbol=XBTUSD&resolution=1&from=1483109940&to=1483196340'

In [81]:
r = requests.get(com)

In [82]:
ret = r.json()

In [83]:
ret

{'s': 'no_data'}

In [58]:
pd.DataFrame(ret)

           c       h       l       o   s           t        v
0     7409.0  7416.5  7402.0  7402.0  ok  1527309240  2949026
1     7408.5  7415.0  7407.0  7409.0  ok  1527309300  2868649
2     7402.0  7409.0  7401.0  7408.5  ok  1527309360  1623783
3     7406.5  7406.5  7401.5  7402.0  ok  1527309420   529559
4     7406.5  7406.5  7406.0  7406.5  ok  1527309480   102136
5     7406.5  7406.5  7406.0  7406.5  ok  1527309540    99527
6     7408.5  7408.5  7406.0  7406.5  ok  1527309600   343215
7     7410.0  7410.5  7408.0  7408.5  ok  1527309660   240175
8     7407.0  7410.5  7406.5  7410.0  ok  1527309720   510370
9     7404.5  7407.0  7404.0  7407.0  ok  1527309780   936561
10    7403.5  7405.0  7403.0  7404.5  ok  1527309840   249545
11    7403.5  7403.5  7403.0  7403.5  ok  1527309900   266529
12    7403.5  7403.5  7403.0  7403.5  ok  1527309960   621937
13    7403.0  7403.5  7403.0  7403.5  ok  1527310020    99412
14    7403.0  7403.5  7403.0  7403.0  ok  1527310080    75923
15    7390.0  7403.5  7390.0  7403.0  ok  1527310140  2308648
16    7388.5  7392.5  7388.5  7390.0  ok  1527310200  1574205
17    7376.0  7389.0  7374.0  7388.5  ok  1527310260  4922366
18    7387.0  7388.5  7376.0  7376.0  ok  1527310320  3118689
19    7386.0  7388.0  7382.5  7387.0  ok  1527310380  1442788
20    7379.0  7386.0  7378.5  7386.0  ok  1527310440  2390032
21    7382.0  7385.0  7379.0  7379.0  ok  1527310500   959992
22    7389.0  7389.0  7382.0  7382.0  ok  1527310560  1542492
23    7389.5  7390.0  7388.5  7389.0  ok  1527310620   940543
24    7389.5  7390.0  7389.5  7389.5  ok  1527310680   551653
25    7387.0  7390.0  7385.0  7389.5  ok  1527310740  1291925
26    7380.0  7388.0  7380.0  7387.0  ok  1527310800  1757842
27    7375.5  7380.5  7375.0  7380.0  ok  1527310860  2022469
28    7388.5  7392.5  7375.0  7375.5  ok  1527310920  2755699
29    7382.0  7388.0  7382.0  7388.5  ok  1527310980   722412
...      ...     ...     ...     ...  ..         ...      ...
1411  7283.0  7293.0  7281.0  7287.0  ok  1527393900  4127532
1412  7286.0  7286.0  7283.5  7283.0  ok  1527393960   116213
1413  7285.5  7286.0  7285.5  7286.0  ok  1527394020    98405
1414  7286.5  7286.5  7285.5  7285.5  ok  1527394080   243390
1415  7295.0  7300.0  7286.0  7286.5  ok  1527394140  2550317
1416  7294.5  7295.0  7294.0  7295.0  ok  1527394200   595697
1417  7295.5  7295.5  7294.0  7294.5  ok  1527394260   304369
1418  7304.5  7305.0  7295.0  7295.5  ok  1527394320  4988825
1419  7298.5  7304.5  7298.0  7304.5  ok  1527394380  2133471
1420  7300.0  7301.0  7298.5  7298.5  ok  1527394440   425289
1421  7298.5  7300.5  7298.0  7300.0  ok  1527394500   822387
1422  7298.0  7298.5  7298.0  7298.5  ok  1527394560   447572
1423  7301.0  7302.5  7298.0  7298.0  ok  1527394620   438649
1424  7302.5  7302.5  7300.5  7301.0  ok  1527394680   334048
1425  7303.0  7303.0  7302.0  7302.5  ok  1527394740   676952
1426  7306.5  7307.0  7302.5  7303.0  ok  1527394800  1644493
1427  7304.5  7306.5  7304.5  7306.5  ok  1527394860   348884
1428  7305.0  7305.0  7304.5  7304.5  ok  1527394920    92686
1429  7307.0  7307.0  7304.5  7305.0  ok  1527394980   542368
1430  7308.5  7308.5  7306.5  7307.0  ok  1527395040   633385
1431  7309.0  7309.0  7308.5  7308.5  ok  1527395100   679647
1432  7303.0  7309.0  7300.0  7309.0  ok  1527395160  2623835
1433  7305.0  7305.5  7300.0  7303.0  ok  1527395220  1305219
1434  7305.5  7305.5  7305.0  7305.0  ok  1527395280    44357
1435  7305.5  7305.5  7305.0  7305.5  ok  1527395340   150434
1436  7299.5  7305.5  7299.5  7305.5  ok  1527395400   916427
1437  7296.5  7299.5  7295.0  7299.5  ok  1527395460  1664965
1438  7300.0  7300.5  7296.5  7296.5  ok  1527395520  1073237
1439  7297.5  7300.5  7297.0  7300.0  ok  1527395580   891269
1440  7297.5  7297.5  7297.0  7297.5  ok  1527395640   145904

[1441 rows x 7 columns]

In [1]:
import mysql.connector

In [3]:
cnt = mysql.connector.connect(
    host='localhost',
    port='3306',
    db='bitmex',
    user='bitmex',
    password='bitmex',
    charset='utf8'
)

In [4]:
cnt

In [5]:
connected = cnt.is_connected()

In [6]:
connected

True

In [8]:
cur = cnt.cursor()

In [10]:
cur.execute('create table hist1m (t int(11), o float(6,1), h float(6,1), l float(6,1), c float(6,1), v int(11))' )

In [12]:
cnt.commit()

In [28]:
h = list(zip(ret['t'], ret['o'], ret['h'], ret['l'], ret['c'], ret['v']))

In [29]:
h[0]

(1527359040, 7547, 7549, 7546.5, 7549, 349512)

In [30]:
sql = 'insert into hist1m values (%s, %s, %s, %s, %s, %s)'

In [31]:
cur.executemany(sql, h)

In [32]:
cnt.commit()

In [ ]:
start_time

In [62]:
datetime(2018,5,26,23,59)

datetime.datetime(2018, 5, 26, 23, 59)

In [71]:
d = datetime.today()

In [74]:
d2 = datetime(d.year, d.month, d.day, 23, 59)

In [75]:
d2

datetime.datetime(2018, 5, 27, 23, 59)